---

#
# sends out network traffic
#
- hosts: source
  sudo: yes
  vars:
    pcap_replay_interface: "enp0s8"
  roles:
    - role: pcap-replay

#
# forwards traffic from one network to another
#
- hosts: router
  sudo: yes
  vars:
      dpdk_device: ["00:08.0","00:09.0"]
      dpdk_target: "x86_64-native-linuxapp-gcc"
      num_huge_pages: 64
  roles:
    - role: dpdk

#
# captures the network traffic that has been forwarded
#
- hosts: sink
  sudo: yes
  vars:
    sniff_interface: "enp0s8"
  tasks:

  - name: Install dependencies
    yum: name=* state=present
    with_items:
      - "@Development tools"
      - pciutils
      - net-tools
      - bind-utils
      - tcpdump

  - name: Turn on promiscuous mode for {{ sniff_interface }}
    shell: "ip link set {{ sniff_interface }} promisc on"
