---
- name: dpdk
  src: https://github.com/nickwallen/metron-provision-dpdk.git

- name: pcap-replay
  src: https://github.com/nickwallen/metron-provision-pcap-replay.git

- name: kafka
  src: https://github.com/nickwallen/metron-provision-kafka.git
