

Vagrant.configure("2") do |config|

  # enable hostmanager
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  #
  # source
  #
  config.vm.define "source" do |node|
    node.vm.hostname = "source"
    node.vm.box = "bento/centos-7.1"
    node.vm.network :private_network, ip: "192.168.33.10", netmask: "255.255.255.0"
    node.ssh.insert_key = "true"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    node.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

  #
  # packet capture
  #
  config.vm.define "capture" do |node|
    node.vm.hostname = "router"
    node.vm.box = "bento/centos-7.1"
    node.vm.network :private_network, ip: "192.168.33.11", netmask: "255.255.255.0"
    node.vm.network :private_network, ip: "192.168.99.10", netmask: "255.255.255.0"
    node.ssh.insert_key = "true"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 3
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    end
    node.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end
end
