---

#
# produces network traffic
#
- hosts: source
  sudo: yes
  vars:
    pcap_replay_interface: "enp0s8"
  roles:
    - role: pcap-replay

#
# consumes network traffic
#
- hosts: sink
  sudo: yes
  vars:
      dpdk_device: ["00:08.0"]
      dpdk_target: "x86_64-native-linuxapp-gcc"
      num_huge_pages: 512
  roles:
    - role: dpdk
    - role: librdkafka
    - role: kafka
