---

#
# produces network traffic
#
- hosts: source
  become: yes
  vars:
    pcap_replay_interface: "enp0s8"
  roles:
    - role: pcap-replay

#
# consumes network traffic
#
- hosts: sink
  become: yes
  vars:
      dpdk_device: ["00:08.0"]
      dpdk_target: "x86_64-native-linuxapp-gcc"
      num_huge_pages: 512
      paccelerate_portmask: 0x2
      paccelerate_topic: pcap
      kafka_broker_url: sink:9092
  roles:
    - role: librdkafka
    - role: kafka
    - role: paccelerate
